import styled from "styled-components";
import Carousel from "../carousel/carousel";

const ProjectDetailTitleStyled = styled.h1`
  font-size: 2rem;

  animation: shadow-pop-tl 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) both;
  -webkit-animation: shadow-pop-tl 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) both;

  /* ----------------------------------------------
 * Generated by Animista on 2021-3-5 21:48:36
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation shadow-pop-tl
 * ----------------------------------------
 */
  @-webkit-keyframes shadow-pop-tl {
    0% {
      -webkit-box-shadow: 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e,
        0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e;
      box-shadow: 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e,
        0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e;
      -webkit-transform: translateX(0) translateY(0);
      transform: translateX(0) translateY(0);
    }
    100% {
      -webkit-box-shadow: -1px -1px #3e3e3e, -2px -2px #3e3e3e, -3px -3px #3e3e3e,
        -4px -4px #3e3e3e, -5px -5px #3e3e3e, -6px -6px #3e3e3e, -7px -7px #3e3e3e,
        -8px -8px #3e3e3e;
      box-shadow: -1px -1px #3e3e3e, -2px -2px #3e3e3e, -3px -3px #3e3e3e,
        -4px -4px #3e3e3e, -5px -5px #3e3e3e, -6px -6px #3e3e3e, -7px -7px #3e3e3e,
        -8px -8px #3e3e3e;
      -webkit-transform: translateX(8px) translateY(8px);
      transform: translateX(8px) translateY(8px);
    }
  }
  @keyframes shadow-pop-tl {
    0% {
      -webkit-box-shadow: 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e,
        0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e;
      box-shadow: 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e,
        0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e;
      -webkit-transform: translateX(0) translateY(0);
      transform: translateX(0) translateY(0);
    }
    100% {
      -webkit-box-shadow: -1px -1px #3e3e3e, -2px -2px #3e3e3e, -3px -3px #3e3e3e,
        -4px -4px #3e3e3e, -5px -5px #3e3e3e, -6px -6px #3e3e3e, -7px -7px #3e3e3e,
        -8px -8px #3e3e3e;
      box-shadow: -1px -1px #3e3e3e, -2px -2px #3e3e3e, -3px -3px #3e3e3e,
        -4px -4px #3e3e3e, -5px -5px #3e3e3e, -6px -6px #3e3e3e, -7px -7px #3e3e3e,
        -8px -8px #3e3e3e;
      -webkit-transform: translateX(8px) translateY(8px);
      transform: translateX(8px) translateY(8px);
    }
  }
`;

const ProjectImgStyled = styled.img`
  width: 100%;
`;

export const Item1 = (
  <div>
    <ProjectDetailTitleStyled>에이콘 이스케이프</ProjectDetailTitleStyled>
    <img
      // src="https://res.cloudinary.com/dmglufkmz/image/upload/c_scale,h_768,w_1024/v1614845131/escape_jsp_y8szx7.wepb"
      src="https://res.cloudinary.com/dmglufkmz/image/upload/v1614955539/escape_jsp_y8szx7.gif"
      alt="에이콘 이스케이프 사진입니다"
      style={{
        width: "100%",
      }}
    />
    <h3>사용 기술</h3>
    <span>Java, Javascript, Oracle</span>
    <h3>개발 목표</h3>
    <span>
      기존 상용중인 사이트(큐브이스케이프)를 개선시키는 작업을 목표로 사이트를 개발한다
    </span>
    <h3>수행 내용</h3>
    <span>
      프로젝트에서 팀장을 맡았으며 동료들이 원하는 페이지를 각자 원하는 기술로 구현하게
      하였고, 각 브랜치들을 취합하여 프로젝트를 완성함
    </span>
    <p>역할 : 프로젝트 팀장, GIT 관리, 팀원 코딩 도움</p>
    <p>작업 내용 : 메인, Escape, 테마, 예약관리, 후기게시판 페이지</p>
  </div>
);
export const Item2 = (
  <div>
    <ProjectDetailTitleStyled>Choi 이스케이프</ProjectDetailTitleStyled>
    <Carousel
      images={[
        "https://res.cloudinary.com/dmglufkmz/image/upload/c_scale,h_768,w_1024/v1614845131/cardmaker1_k4gcr5.webp",
        "https://res.cloudinary.com/dmglufkmz/image/upload/c_scale,h_768,w_1024/v1614845131/cardmaker2_gio3dt.webp",
      ]}
    />
    <h3>사용 기술</h3>
    <span>Java, Javascript, React, Oracle</span>
    <h3>개발 목표</h3>
    <p>학원에서 진행하였던 팀플 프로젝트를 React로 변경하는것을 목표로 한다</p>
    <h3>수행 내용</h3>
    <p>
      프로젝트 모든 내용 진행 <br />
      백엔드 서버 재설계 진행 (API) 운영 서버 구축 (Docker compose, tomcat, Linux) <br />
      프론트엔드 REACT로 개발 진행함.
      <br />
    </p>
  </div>
);

export const Item3 = (
  <div>
    <ProjectDetailTitleStyled>HLS12 PC GUI</ProjectDetailTitleStyled>
    {/* <img
      src="https://res.cloudinary.com/dmglufkmz/image/upload/c_scale,h_768,w_1024/v1614845131/rabbit_sfbjrs.gif"
      art="프로젝트"
      style={{ width: "100%" }}
    ></img> */}
    <div
      style={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <iframe
        width="560"
        height="315"
        title="HLS12 PC GUI"
        src="https://www.youtube.com/embed/q-asGOQOAeo"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen
      ></iframe>
    </div>
    <h3>사용 기술</h3>
    <span>C#, WPF, 회로개발, 펌웨어개발</span>
    <h3>개발 목표</h3>
    <p>학원에서 진행하였던 팀플 프로젝트를 React로 변경하는것을 목표로 한다</p>
    <h3>수행 내용</h3>
    <p>
      프로젝트 모든 내용 진행 <br />
      백엔드 서버 재설계 진행 (API) 운영 서버 구축 (Docker compose, tomcat, Linux) <br />
      프론트엔드 REACT로 개발 진행함.
      <br />
    </p>
  </div>
);
export const Item4 = (
  <div>
    <ProjectDetailTitleStyled>HLS12</ProjectDetailTitleStyled>
    <Carousel
      images={[
        "https://res.cloudinary.com/dmglufkmz/image/upload/c_scale,h_768,w_1024/v1614845131/리니어서보1_fv4ano.webp",
        "https://res.cloudinary.com/dmglufkmz/image/upload/c_scale,h_768,w_1024/v1614845131/20190723_144051_mavupf.webp",
      ]}
    />
    <h3>사용 기술</h3>
    <span>FPCB 회로개발</span>
    <h3>개발 목표</h3>
    <p>리니어서보 개발을 위한 회로를 개발한다. </p>
    <h3>수행 내용</h3>
    <p>
      기존 일반 서보모터의 PCB를 FPCB로 재설계하였음.
      <br />
      제품에 사용할 모터 채택과 pcb를 개발하여 제품을 완성하였음.
      <br />
      제품의 회로파트를 담당였음.
      <br />
    </p>
  </div>
);

export const Item6 = (
  <div>
    <ProjectDetailTitleStyled>rabbit</ProjectDetailTitleStyled>
    <img
      // src="https://res.cloudinary.com/dmglufkmz/image/upload/c_scale,h_768,w_1024/v1614845131/escape_jsp_y8szx7.wepb"
      src="https://res.cloudinary.com/dmglufkmz/image/upload/v1614845518/rabbit_sfbjrs.gif"
      alt="에이콘 이스케이프 사진입니다"
      style={{
        width: "100%",
      }}
    />
    <h1>dd</h1>
    <h3>사용 기술</h3>
    <span>FPCB 회로개발</span>
    <h3>개발 목표</h3>
    <p>리니어서보 개발을 위한 회로를 개발한다. </p>
    <h3>수행 내용</h3>
    <p>
      기존 일반 서보모터의 PCB를 FPCB로 재설계하였음.
      <br />
      제품에 사용할 모터 채택과 pcb를 개발하여 제품을 완성하였음.
      <br />
      제품의 회로파트를 담당였음.
      <br />
    </p>
  </div>
);
export const Item7 = (
  <div>
    <ProjectDetailTitleStyled>rabbit</ProjectDetailTitleStyled>
    <Carousel
      images={[
        "https://res.cloudinary.com/dmglufkmz/image/upload/c_scale,h_768,w_1024/v1614845131/리니어서보1_fv4ano.webp",
        "https://res.cloudinary.com/dmglufkmz/image/upload/c_scale,h_768,w_1024/v1614845131/20190723_144051_mavupf.webp",
      ]}
    />
    <h3>사용 기술</h3>
    <span>FPCB 회로개발</span>
    <h3>개발 목표</h3>
    <p>리니어서보 개발을 위한 회로를 개발한다. </p>
    <h3>수행 내용</h3>
    <p>
      기존 일반 서보모터의 PCB를 FPCB로 재설계하였음.
      <br />
      제품에 사용할 모터 채택과 pcb를 개발하여 제품을 완성하였음.
      <br />
      제품의 회로파트를 담당였음.
      <br />
    </p>
  </div>
);
