import React from "react";
import styled from "styled-components";
const FooterStyle = styled.footer`
  display: flex;
  justify-content: center;
  align-items: center;
  position: fixed;
  bottom: 0;
  width: 100%;
  height: 5%;
  &:hover {
    cursor: pointer;
  }
  // border-top: 1px solid black;
  font-size: 1rem;

  -webkit-animation: text-pop-up-top 1.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) infinite
    alternate both;
  animation: text-pop-up-top 1.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) infinite alternate
    both;

  /* ----------------------------------------------
 * Generated by Animista on 2021-3-7 22:52:19
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation text-pop-up-top
 * ----------------------------------------
 */
  @-webkit-keyframes text-pop-up-top {
    0% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-transform-origin: 30% 30%;
      transform-origin: 30% 30%;
      text-shadow: none;
    }
    100% {
      -webkit-transform: translateY(-10px);
      transform: translateY(-10px);
      -webkit-transform-origin: 30% 30%;
      transform-origin: 30% 30%;
      text-shadow: 0 1px 0 #cccccc, 0 2px 0 #cccccc, 0 3px 0 #cccccc, 0 4px 0 #cccccc,
        0 5px 0 #cccccc, 0 6px 0 #cccccc, 0 7px 0 #cccccc, 0 8px 0 #cccccc,
        0 9px 0 #cccccc, 0 50px 30px rgba(0, 0, 0, 0.3);
    }
  }
  @keyframes text-pop-up-top {
    0% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-transform-origin: 30% 30%;
      transform-origin: 30% 30%;
      text-shadow: none;
    }
    100% {
      -webkit-transform: translateY(-10px);
      transform: translateY(-10px);
      -webkit-transform-origin: 30% 30%;
      transform-origin: 30% 30%;
      text-shadow: 0 1px 0 #cccccc, 0 2px 0 #cccccc, 0 3px 0 #cccccc, 0 4px 0 #cccccc,
        0 5px 0 #cccccc, 0 6px 0 #cccccc, 0 7px 0 #cccccc, 0 8px 0 #cccccc,
        0 9px 0 #cccccc, 0 50px 30px rgba(0, 0, 0, 0.3);
    }
  }
`;

const Footer = (props) => {
  return (
    <>
      <FooterStyle
        onClick={() => {
          document.location.href = "tel:010-2325-1002";
        }}
      >
        📞 010-2325-1002(Click)
      </FooterStyle>
    </>
  );
};

export default Footer;
