import React from "react";
import styled from "styled-components";
const FooterStyle = styled.footer`
  display: flex;
  justify-content: center;
  align-items: center;

  height: 15%;
  &:hover {
    cursor: pointer;
  }
  // border-top: 1px solid black;
  font-size: 2rem;

  -webkit-animation: shake-top 3s cubic-bezier(0.455, 0.03, 0.515, 0.955) infinite;
  animation: shake-top 3s cubic-bezier(0.455, 0.03, 0.515, 0.955) infinite;

  /* ----------------------------------------------
  * Generated by Animista on 2021-2-25 20:22:34
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
  * ----------------------------------------
  * animation shake-top
  * ----------------------------------------
  */
  @-webkit-keyframes shake-top {
    0%,
    100% {
      -webkit-transform: rotate(0deg);
      transform: rotate(0deg);
      -webkit-transform-origin: 50% 0;
      transform-origin: 50% 0;
    }
    10% {
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
    20%,
    40%,
    60% {
      -webkit-transform: rotate(-4deg);
      transform: rotate(-4deg);
    }
    30%,
    50%,
    70% {
      -webkit-transform: rotate(4deg);
      transform: rotate(4deg);
    }
    80% {
      -webkit-transform: rotate(-2deg);
      transform: rotate(-2deg);
    }
    90% {
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
  }
  @keyframes shake-top {
    0%,
    100% {
      -webkit-transform: rotate(0deg);
      transform: rotate(0deg);
      -webkit-transform-origin: 50% 0;
      transform-origin: 50% 0;
    }
    10% {
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
    20%,
    40%,
    60% {
      -webkit-transform: rotate(-4deg);
      transform: rotate(-4deg);
    }
    30%,
    50%,
    70% {
      -webkit-transform: rotate(4deg);
      transform: rotate(4deg);
    }
    80% {
      -webkit-transform: rotate(-2deg);
      transform: rotate(-2deg);
    }
    90% {
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
  }
`;
const Foot = styled.footer``;

const Footer = (props) => {
  return (
    <>
      <FooterStyle
        onClick={() => {
          document.location.href = "tel:010-2325-1002";
        }}
      >
        📞 010-2325-1002 ✨
      </FooterStyle>
    </>
  );
};

export default Footer;
